name: BabyRobotGym
channels:
  - defaults
dependencies:
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - ncurses=6.3
  - fontconfig=2.13.1
  - dbus=1.13.18
  - libuuid=1.0.3
  - _openmp_mutex=4.5
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - ld_impl_linux-64=2.35.1
  - libxcb=1.14
  - freetype=2.11.0
  - libffi=3.3
  - libstdcxx-ng=9.3.0
  - readline=8.1.2