name: BabyRobotGym
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - bleach=4.1.0
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.4.4
  - fontconfig=2.13.1
  - freetype=2.11.0
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jinja2=3.0.3
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.12
  - matplotlib-inline=0.1.2
  - ncurses=6.3
  - openssl=1.1.1n
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - send2trash=1.8.0
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - stack_data=0.2.0
  - testpath=0.5.0
  - tk=8.6.11
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - pip:
    - argon2-cffi-bindings==21.2.0
    - beautifulsoup4==4.11.1
    - certifi==2021.5.30
    - cffi==1.15.0
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - debugpy==1.5.1
    - entrypoints==0.4
    - fonttools==4.33.3
    - gym==0.21.0
    - ipykernel==6.9.1
    - ipython==8.2.0
    - jedi==0.18.1
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.2.2
    - jupyter-core==4.9.2
    - kiwisolver==1.4.2
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - mistune==0.8.4
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - notebook==6.4.8
    - numpy==1.22.3
    - pandas==1.4.2
    - pillow==9.1.0
    - pip==21.2.4
    - pyrsistent==0.18.0
    - pytz==2022.1
    - pyzmq==22.3.0
    - setuptools==61.2.0
    - sip==4.19.13
    - stable-baselines3==1.5.0
    - terminado==0.13.1
    - torch==1.11.0
    - tornado==6.1
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
